export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export NIXOS_CONFIG_DIR="$XDG_CONFIG_HOME/nixos"
# export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship"
# Test live update