# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Boot configuration for mini PC Axon
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ]; # Change to "kvm-amd" for AMD processors
  boot.extraModulePackages = [ ];

  # Disk configuration - adjust as needed for your mini PC
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";  # Replace with actual UUID
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/XXXX-XXXX";  # Replace with actual UUID
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  # Swap configuration (optional for Axon)
  swapDevices = [ ];

  # Networking
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s25.useDHCP = lib.mkDefault true;  # Adjust interface name as needed

  # Hardware configuration
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # For AMD processors, use instead:
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Hardware video acceleration for Intel graphics
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver  # For modern Intel graphics (Broadwell+)
      intel-vaapi-driver  # For older Intel graphics
    ];
  };

  # Enable firmware updates
  services.fwupd.enable = true;

  # Power management for mini PC
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}

# NOTE: You'll need to update the UUIDs and potentially the interface names
# after installing NixOS on your mini PC hardware.
# Run 'nixos-generate-config' on the target machine to get the correct values.