# OpenCode Feature Module
#
# Manages the opencode.json configuration fully declaratively through Nix.
# The sync script (`opencode-lmstudio-sync`) queries the LM Studio API and
# updates the Nix source file (lmstudio-models.nix), then you rebuild.
#
# Usage:
#   modules.features.opencode = {
#     enable = true;
#     lmstudio = {
#       baseURL = "http://192.168.1.7:1234/v1";
#       modelsFile = ./lmstudio-models.nix;  # auto-generated by sync script
#     };
#   };
#
# Workflow:
#   1. Run `opencode-lmstudio-sync` to discover models and update the .nix file
#   2. Rebuild with `nos` to regenerate opencode.json
#   3. Models are now available in opencode's /models list

{
  config,
  lib,
  pkgs,
  userVars,
  ...
}:

let
  inherit (lib)
    mkEnableOption
    mkOption
    mkIf
    types
    mapAttrs
    ;

  cfg = config.modules.features.opencode;
  fleetConfig = import ../../fleet-config.nix;

  # Build the opencode.json structure from Nix options
  opencodeConfig = {
    "$schema" = "https://opencode.ai/config.json";
    provider = lib.optionalAttrs cfg.lmstudio.enable {
      lmstudio = {
        npm = "@ai-sdk/openai-compatible";
        name = cfg.lmstudio.name;
        options = {
          baseURL = cfg.lmstudio.baseURL;
        } // lib.optionalAttrs (cfg.lmstudio.apiKey != null) {
          apiKey = cfg.lmstudio.apiKey;
        };
        models = mapAttrs (
          id: modelCfg:
          { inherit (modelCfg) name; }
          // lib.optionalAttrs (modelCfg.context != null || modelCfg.output != null) {
            limit =
              lib.optionalAttrs (modelCfg.context != null) { inherit (modelCfg) context; }
              // lib.optionalAttrs (modelCfg.output != null) { inherit (modelCfg) output; };
          }
        ) cfg.lmstudio.models;
      };
    } // cfg.extraProviders;
  } // cfg.extraConfig;

  # Path to the models file that the sync script will update
  defaultModelsFile = ../../systems/orion/lmstudio-models.nix;

  # Sync script: queries LM Studio API, updates the Nix models file
  syncScript = pkgs.writeShellScriptBin "opencode-lmstudio-sync" ''
    set -euo pipefail

    MODELS_FILE="${cfg.lmstudio.modelsFile}"
    BASE_URL="${cfg.lmstudio.baseURL}"
    API_URL="''${BASE_URL%/v1}/v1/models"

    echo "Querying LM Studio at $API_URL ..."

    RESPONSE=$(${pkgs.curl}/bin/curl -sf --connect-timeout 5 "$API_URL" 2>/dev/null) || {
      echo "Error: Could not reach LM Studio at $API_URL" >&2
      echo "Is LM Studio running on cortex?" >&2
      exit 1
    }

    # Extract model IDs from the API response
    REMOTE_MODELS=$(echo "$RESPONSE" | ${pkgs.jq}/bin/jq -r '.data[].id' 2>/dev/null) || {
      echo "Error: Unexpected API response format" >&2
      exit 1
    }

    if [ -z "$REMOTE_MODELS" ]; then
      echo "No models found on LM Studio server."
      exit 0
    fi

    # Read existing models from the Nix file (if it exists) to preserve
    # any manually set context/output limits
    declare -A EXISTING_CONTEXT
    declare -A EXISTING_OUTPUT
    if [ -f "$MODELS_FILE" ]; then
      # Parse existing entries -- look for context and output values
      while IFS= read -r line; do
        if [[ "$line" =~ ^[[:space:]]*\"(.+)\"[[:space:]]*= ]]; then
          current_id="''${BASH_REMATCH[1]}"
        fi
        if [[ "$line" =~ context[[:space:]]*=[[:space:]]*([0-9]+) ]]; then
          EXISTING_CONTEXT["$current_id"]="''${BASH_REMATCH[1]}"
        fi
        if [[ "$line" =~ output[[:space:]]*=[[:space:]]*([0-9]+) ]]; then
          EXISTING_OUTPUT["$current_id"]="''${BASH_REMATCH[1]}"
        fi
      done < "$MODELS_FILE"
    fi

    # Generate the Nix models file
    {
      echo "# LM Studio models - auto-generated by opencode-lmstudio-sync"
      echo "# Last updated: $(date -Iseconds)"
      echo "# Source: $API_URL"
      echo "#"
      echo "# To refresh: run opencode-lmstudio-sync && nos"
      echo "# To add context/output limits, edit manually -- they will be preserved on sync."
      echo "{"

      while IFS= read -r model_id; do
        [ -z "$model_id" ] && continue
        # Generate display name: last path component, hyphens to spaces, title-case
        display_name=$(echo "$model_id" | ${pkgs.gawk}/bin/awk -F/ '{print $NF}' | sed 's/-/ /g; s/\b\(.\)/\u\1/g')

        # Check for preserved limits
        ctx="''${EXISTING_CONTEXT[$model_id]:-}"
        out="''${EXISTING_OUTPUT[$model_id]:-}"

        if [ -n "$ctx" ] || [ -n "$out" ]; then
          echo "  \"$model_id\" = {"
          echo "    name = \"$display_name\";"
          [ -n "$ctx" ] && echo "    context = $ctx;"
          [ -n "$out" ] && echo "    output = $out;"
          echo "  };"
        else
          echo "  \"$model_id\" = { name = \"$display_name\"; };"
        fi
      done <<< "$REMOTE_MODELS"

      echo "}"
    } > "$MODELS_FILE"

    MODEL_COUNT=$(echo "$REMOTE_MODELS" | wc -l)
    echo ""
    echo "Updated $MODELS_FILE with $MODEL_COUNT models."
    echo "Run 'nos' to rebuild and apply."
  '';
in
{
  # ===== OPTIONS =====

  options.modules.features.opencode = {
    enable = mkEnableOption "OpenCode AI coding agent configuration";

    lmstudio = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Enable LM Studio as an OpenCode provider";
      };

      name = mkOption {
        type = types.str;
        default = "LM Studio";
        description = "Display name for the LM Studio provider in OpenCode";
      };

      baseURL = mkOption {
        type = types.str;
        default = "http://${fleetConfig.hosts.cortex.ip}:1234/v1";
        description = "Base URL for the LM Studio API endpoint";
      };

      apiKey = mkOption {
        type = types.nullOr types.str;
        default = null;
        description = "API key for LM Studio (usually not needed for local instances)";
      };

      modelsFile = mkOption {
        type = types.str;
        default = "$HOME/.config/nixos/systems/orion/lmstudio-models.nix";
        description = "Path to the Nix models file that the sync script updates";
      };

      models = mkOption {
        type = types.attrsOf (
          types.submodule {
            options = {
              name = mkOption {
                type = types.str;
                description = "Display name for the model";
              };
              context = mkOption {
                type = types.nullOr types.int;
                default = null;
                description = "Context window size (tokens). Leave null for server default.";
              };
              output = mkOption {
                type = types.nullOr types.int;
                default = null;
                description = "Max output tokens. Leave null for server default.";
              };
            };
          }
        );
        default = { };
        description = ''
          LM Studio models to make available in OpenCode.
          Typically imported from lmstudio-models.nix (auto-generated by sync script).
        '';
      };
    };

    extraProviders = mkOption {
      type = types.attrs;
      default = { };
      description = "Additional provider configurations to merge into opencode.json";
    };

    extraConfig = mkOption {
      type = types.attrs;
      default = { };
      description = "Additional top-level opencode.json settings (e.g. model, share)";
    };
  };

  # ===== CONFIGURATION =====

  config = mkIf cfg.enable {

    home-manager.users.${userVars.username} = {

      # Install the sync script
      home.packages = [
        syncScript
      ];

      # Generate opencode.json declaratively from Nix
      xdg.configFile."opencode/opencode.json" = {
        text = builtins.toJSON opencodeConfig;
      };
    };
  };
}
