{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  inherit (lib) mkEnableOption mkIf;
  cfg = config.modules.features.swhkd;
in
{
  options.modules.features.swhkd = {
    enable = mkEnableOption "swhkd - Simple Wayland HotKey Daemon for compositor-agnostic keybindings";
  };

  config = mkIf cfg.enable {
    security.wrappers.swhkd = {
      source = "${inputs.swhkd.packages.${pkgs.stdenv.hostPlatform.system}.default}/bin/swhkd";
      owner = "root";
      group = "root";
      setuid = true;
    };

    home-manager.sharedModules = [
      (
        {
          config,
          pkgs,
          userVars,
          ...
        }:
        let
          swhkdConfigPath = "/home/${userVars.username}/.config/swhkd/swhkdrc";
          hyprCfg = userVars.hyprland or { };
          terminal = hyprCfg.terminal or "ghostty";
          fileManager = hyprCfg.fileManager or "nemo";
          webBrowser = hyprCfg.webBrowser or "brave";
          menu = hyprCfg.menu or "rofi -show drun";
          hostName = userVars.hostName or "orion";
          configRoot = "/home/${userVars.username}/.config/nixos";
          scriptsDir = "${configRoot}/scripts";
          hostScriptsDir = "${configRoot}/systems/${hostName}/scripts";
          lockCmd = "noctalia-shell ipc call lockScreen lock";

          swhkdConfig = ''
            # ═══════════════════════════════════════════════════════════════════════════════
            # SWHKD Configuration - Compositor-agnostic system keybindings
            # ═══════════════════════════════════════════════════════════════════════════════
            # This file is generated by NixOS from features/swhkd.nix
            # Shell-specific commands are configured in systems/<host>/variables.nix
            #
            # Syntax is sxhkd-compatible: https://man.archlinux.org/man/sxhkd.1


            # ─────────────────────────────────────────────────────────────────────────────────
            # Application Launchers
            # ─────────────────────────────────────────────────────────────────────────────────

            # Terminal
            super + Return
                ${terminal}

            # Application menu
            super + d
                ${menu}

            # File manager
            super + e
                ${fileManager}

            # Web browser
            super + w
                ${webBrowser}

            # Brave with optimizations
            super + b
                ${scriptsDir}/browser/brave-optimized.sh

            # Wallpaper picker
            super + alt + w
                waypaper


            # ─────────────────────────────────────────────────────────────────────────────────
            # Screenshots
            # ─────────────────────────────────────────────────────────────────────────────────

            # Full screenshot
            super + ctrl + s
                ${scriptsDir}/desktop/screenshot.sh full

            # Area screenshot
            super + ctrl + shift + s
                ${scriptsDir}/desktop/screenshot.sh area

            # macOS-style: full screenshot
            super + ctrl + shift + 3
                ${scriptsDir}/desktop/screenshot.sh full

            # macOS-style: area screenshot
            super + ctrl + shift + 4
                ${scriptsDir}/desktop/screenshot.sh area


            # ─────────────────────────────────────────────────────────────────────────────────
            # System Controls
            # ─────────────────────────────────────────────────────────────────────────────────

            # Screen lock (via noctalia-shell)
            super + ctrl + q
                ${lockCmd}

            # Monitor handler
            super + ctrl + shift + m
                ${hostScriptsDir}/monitor-handler.sh --fast


            # ─────────────────────────────────────────────────────────────────────────────────
            # Media Keys
            # ─────────────────────────────────────────────────────────────────────────────────

            # Volume controls
            XF86AudioRaiseVolume
                ${scriptsDir}/desktop/volume-control.sh up

            XF86AudioLowerVolume
                ${scriptsDir}/desktop/volume-control.sh down

            XF86AudioMute
                ${scriptsDir}/desktop/volume-control.sh mute

            XF86AudioMicMute
                wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle


            # ─────────────────────────────────────────────────────────────────────────────────
            # Brightness Keys
            # ─────────────────────────────────────────────────────────────────────────────────

            XF86MonBrightnessUp
                brightnessctl s 10%+

            XF86MonBrightnessDown
                brightnessctl s 10%-


            # ─────────────────────────────────────────────────────────────────────────────────
            # Media Playback
            # ─────────────────────────────────────────────────────────────────────────────────

            XF86AudioPlay
                playerctl play-pause

            XF86AudioNext
                playerctl next

            XF86AudioPrev
                playerctl previous
          '';
        in
        {
          home.packages = [
            inputs.swhkd.packages.${pkgs.stdenv.hostPlatform.system}.default
          ];

          xdg.configFile."swhkd/swhkdrc" = {
            text = swhkdConfig;
          };

          systemd.user.services.swhks = {
            Unit = {
              Description = "Simple Wayland HotKey Server";
              PartOf = [ "graphical-session.target" ];
              After = [ "graphical-session.target" ];
            };
            Service = {
              Type = "forking";
              ExecStart = "${inputs.swhkd.packages.${pkgs.stdenv.hostPlatform.system}.default}/bin/swhks";
              PIDFile = "%t/swhks_%U.pid";
              Restart = "on-failure";
              RestartSec = 1;
            };
            Install = {
              WantedBy = [ "graphical-session.target" ];
            };
          };

          systemd.user.services.swhkd = {
            Unit = {
              Description = "Simple Wayland HotKey Daemon";
              PartOf = [ "graphical-session.target" ];
              After = [
                "graphical-session.target"
                "swhks.service"
              ];
              Requires = [ "swhks.service" ];
            };
            Service = {
              ExecStart = "/run/wrappers/bin/swhkd -c ${swhkdConfigPath}";
              Restart = "on-failure";
            };
            Install = {
              WantedBy = [ "graphical-session.target" ];
            };
          };
        }
      )
    ];
  };
}
