# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "thunderbolt"
      "usb_storage"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-amd" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/031d313c-b2ae-4f1f-aa24-0c3efee4d42c";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-01795ce3-d6bf-4439-b4a9-5352d90b4b1c".device =
    "/dev/disk/by-uuid/01795ce3-d6bf-4439-b4a9-5352d90b4b1c";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/82A6-62FF";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    {
      device = "/swapfile";
      size = 96 * 1024; # 96 GB - sized for hibernation with 92GB RAM
    }
  ];

  # Hibernation support
  # Resume device is the partition containing the swap file
  boot.resumeDevice = "/dev/disk/by-uuid/031d313c-b2ae-4f1f-aa24-0c3efee4d42c";

  # resume_offset for swapfile hibernation (from: sudo filefrag -v /swapfile)
  # If /swapfile is ever recreated, this value must be re-queried and updated.
  boot.kernelParams = [ "resume_offset=173766656" ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
