{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

let
  inherit (lib) mkEnableOption mkIf;
  cfg = config.modules.features.swhkd;
in
{
  options.modules.features.swhkd = {
    enable = mkEnableOption "swhkd - Simple Wayland HotKey Daemon for compositor-agnostic keybindings";
  };

  config = mkIf cfg.enable {
    # swhkd needs to run as root to read input devices
    # We use the setuid approach for better UX
    security.wrappers.swhkd = {
      source = "${inputs.swhkd.packages.${pkgs.system}.default}/bin/swhkd";
      owner = "root";
      group = "root";
      setuid = true;
    };

    # Home-manager configuration
    home-manager.sharedModules = [
      (
        {
          config,
          pkgs,
          userVars,
          ...
        }:
        let
          # Full path to config file for swhkd (runs as root, needs absolute path)
          swhkdConfigPath = "/home/${userVars.username}/.config/swhkd/swhkdrc";

          # Shell-agnostic command configuration from userVars
          # Falls back to generic commands if not specified
          hyprCfg = userVars.hyprland or { };
          terminal = hyprCfg.terminal or "ghostty";
          fileManager = hyprCfg.fileManager or "nemo";
          webBrowser = hyprCfg.webBrowser or "brave";
          menu = hyprCfg.menu or "rofi -show drun";

          # Generate swhkdrc content
          swhkdConfig = ''
            # ═══════════════════════════════════════════════════════════════════════════════
            # SWHKD Configuration - Compositor-agnostic system keybindings
            # ═══════════════════════════════════════════════════════════════════════════════
            # This file is generated by NixOS from features/swhkd.nix
            # Shell-specific commands are configured in systems/<host>/variables.nix
            #
            # Syntax is sxhkd-compatible: https://man.archlinux.org/man/sxhkd.1


            # ─────────────────────────────────────────────────────────────────────────────────
            # Application Launchers
            # ─────────────────────────────────────────────────────────────────────────────────

            # Terminal
            super + Return
                ${terminal}

            # Application menu
            super + d
                ${menu}

            # File manager
            super + e
                ${fileManager}

            # Web browser
            super + w
                ${webBrowser}

            # Brave with optimizations
            super + b
                $HOME/.config/nixos/scripts/browser/brave-optimized.sh

            # Wallpaper picker
            super + alt + w
                waypaper


            # ─────────────────────────────────────────────────────────────────────────────────
            # Screenshots
            # ─────────────────────────────────────────────────────────────────────────────────

            # Full screenshot
            super + ctrl + s
                $HOME/.config/nixos/scripts/desktop/screenshot.sh full

            # Area screenshot
            super + ctrl + shift + s
                $HOME/.config/nixos/scripts/desktop/screenshot.sh area

            # macOS-style: full screenshot
            super + ctrl + shift + 3
                $HOME/.config/nixos/scripts/desktop/screenshot.sh full

            # macOS-style: area screenshot
            super + ctrl + shift + 4
                $HOME/.config/nixos/scripts/desktop/screenshot.sh area


            # ─────────────────────────────────────────────────────────────────────────────────
            # System Controls
            # ─────────────────────────────────────────────────────────────────────────────────

            # Screen lock (hyprlock for Hyprland, swaylock for others)
            super + ctrl + q
                hyprlock

            # Monitor handler
            super + ctrl + shift + m
                $HOME/.config/nixos/systems/orion/scripts/monitor-handler.sh --fast


            # ─────────────────────────────────────────────────────────────────────────────────
            # Media Keys
            # ─────────────────────────────────────────────────────────────────────────────────

            # Volume controls
            XF86AudioRaiseVolume
                $HOME/.config/nixos/scripts/desktop/volume-control.sh up

            XF86AudioLowerVolume
                $HOME/.config/nixos/scripts/desktop/volume-control.sh down

            XF86AudioMute
                $HOME/.config/nixos/scripts/desktop/volume-control.sh mute

            XF86AudioMicMute
                wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle


            # ─────────────────────────────────────────────────────────────────────────────────
            # Brightness Keys
            # ─────────────────────────────────────────────────────────────────────────────────

            XF86MonBrightnessUp
                brightnessctl s 10%+

            XF86MonBrightnessDown
                brightnessctl s 10%-


            # ─────────────────────────────────────────────────────────────────────────────────
            # Media Playback
            # ─────────────────────────────────────────────────────────────────────────────────

            XF86AudioPlay
                playerctl play-pause

            XF86AudioNext
                playerctl next

            XF86AudioPrev
                playerctl previous
          '';
        in
        {
          home.packages = [
            inputs.swhkd.packages.${pkgs.system}.default
          ];

          # Generate swhkd configuration from Nix
          xdg.configFile."swhkd/swhkdrc" = {
            text = swhkdConfig;
          };

          # swhks (the server) runs as user, swhkd (daemon) runs as root
          # Start swhks via systemd user service
          systemd.user.services.swhks = {
            Unit = {
              Description = "Simple Wayland HotKey Server";
              PartOf = [ "graphical-session.target" ];
              After = [ "graphical-session.target" ];
            };
            Service = {
              # swhks daemonizes itself (forks to background), so use forking type
              Type = "forking";
              ExecStart = "${inputs.swhkd.packages.${pkgs.system}.default}/bin/swhks";
              Restart = "on-failure";
              RestartSec = 1;
            };
            Install = {
              WantedBy = [ "graphical-session.target" ];
            };
          };

          # Start swhkd daemon via systemd user service (uses setuid wrapper)
          # Note: swhkd runs as root via setuid, so we must specify the full config path
          systemd.user.services.swhkd = {
            Unit = {
              Description = "Simple Wayland HotKey Daemon";
              PartOf = [ "graphical-session.target" ];
              After = [
                "graphical-session.target"
                "swhks.service"
              ];
              Requires = [ "swhks.service" ];
            };
            Service = {
              ExecStart = "/run/wrappers/bin/swhkd -c ${swhkdConfigPath}";
              Restart = "on-failure";
            };
            Install = {
              WantedBy = [ "graphical-session.target" ];
            };
          };
        }
      )
    ];
  };
}
