live_config_reload = true

[selection]
save_to_clipboard = true

[colors]
draw_bold_text_with_bright_colors = true

# github Alacritty Colors

# Default colors
[colors.primary]
background = '#0d1117'
foreground = '#b3b1ad'

# Normal colors
[colors.normal]
black   = '#484f58'
red     = '#ff7b72'
green   = '#3fb950'
yellow  = '#d29922'
blue    = '#58a6ff'
magenta = '#bc8cff'
cyan    = '#39c5cf'
white   = '#b1bac4'

# Bright colors
[colors.bright]
black   = '#6e7681'
red     = '#ffa198'
green   = '#56d364'
yellow  = '#e3b341'
blue    = '#79c0ff'
magenta = '#d2a8ff'
cyan    = '#56d4dd'
white   = '#f0f6fc'

[[colors.indexed_colors]]
index = 16
color = '#d18616'

[[colors.indexed_colors]]
index = 17
color = '#ffa198'

[colors.hints]
start = { foreground = "#1d1f21", background = "#e9ff5e" }
end = { foreground = "#e9ff5e", background = "#1d1f21" }

[colors.search]
matches = { foreground = "#000000", background = "#ffffff" }
focused_match = { foreground = "#ffffff", background = "#000000" }

[cursor]
style = "Underline"

[env]
TERM = "xterm-256color"

[font]
#size = 10

[font.bold]
family = "FiraCode Nerd Font Mono"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
#size = 12

[font.italic]
family = "FiraCode Nerd Font Mono"

[font.normal]
family = "FiraCode Nerd Font Mono"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "full"
decorations_theme_variant = "Dark"
dynamic_padding = true
opacity = 0.6
title = "Alacritty"
dynamic_title = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30
